# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PP6tkUMrE19CqKoO7TEnjZ_3HTxO_u0W
"""

# Basic usage examples for all 4 of our classes
# Example usage for Meal

m1 = Meal("M1", "Tofu Bowl", 9.99, 450, "vegetarian", "savory")
m1.add_rating(5)
m1.add_rating(4)
print(m1.format_meal())       # e.g., "Tofu Bowl (id:M1) — $9.99, 450 kcal"
print(m1.average_rating)      # 4.5


# Example usage for Menu

menu = Menu([m1])
m2 = Meal("M2", "Chicken Curry", 12.99, 600, "meat", "spicy")
menu.add(m2)
print(menu.average_price())   # 11.49
veg_meals = menu.filter_by_diet("vegetarian")
print([m.name for m in veg_meals])  # ['Tofu Bowl']

# Alternate CSV constructor
csv_text = "id,name,price,calories,diet,flavor\n3,Pasta,11.5,500,vegetarian,creamy"
menu_from_csv, errors = Menu.from_csv(csv_text)
print(errors)  # []

# Example usage for UserPreferences

prefs = UserPreferences(history_ids=["M1"], budget=15.0)
prefs.add_meal_to_history("M2")
print(prefs.history_ids)        # ['M1', 'M2']
print(prefs.check_budget(10))   # True
# Update token weights from menu
prefs.update_preferences(menu.meals)
print(prefs.token_weights)      # e.g., {'savory': 0.5, 'vegetarian': 0.5, ...}

# Example usage for Recommendations

rec = Recommendations(menu.meals)
rec.add_to_history("M1")
recommended = rec.recommend_meals(top_k=2, budget=15.0)
print([m.name for m in recommended])  # ['Tofu Bowl', 'Chicken Curry']
spicy_meal = rec.suggest_by_flavor("spicy")
print(spicy_meal["name"] if spicy_meal else None)  # 'Chicken Curry'
avg_rating = rec.get_average_rating("M1")
print(avg_rating)  # 4.5