# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8yRqNH-UFxtcRH6aNoJ_IT3o4oPIgze
"""

"""Menu class using composition."""

from typing import List, Optional
from meal_items import AbstractMealItem


class Menu:
    """Collection of meal items."""

    def __init__(self):
        self._meals: List[AbstractMealItem] = []

    def add_meal(self, meal: AbstractMealItem) -> None:
        """Add a meal to the menu."""
        self._meals.append(meal)

    def get_meal(self, meal_id: str) -> Optional[AbstractMealItem]:
        """Get meal by ID."""
        for meal in self._meals:
            if meal.id == meal_id:
                return meal
        return None

    def get_all_meals(self) -> List[AbstractMealItem]:
        """Get all meals."""
        return list(self._meals)

    def filter_by_diet(self, diet: str) -> List[AbstractMealItem]:
        """Get meals matching diet type."""
        return [m for m in self._meals if diet.lower() in m.diet.lower()]

    def filter_by_price(self, max_price: float) -> List[AbstractMealItem]:
        """Get meals under max price."""
        return [m for m in self._meals if m.price <= max_price]

    def get_value_scores(self) -> dict:
        """Get value scores for all meals (demonstrates polymorphism)."""
        return {meal.id: meal.calculate_value_score() for meal in self._meals}

    def __len__(self) -> int:
        return len(self._meals)