# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8yRqNH-UFxtcRH6aNoJ_IT3o4oPIgze
"""

"""Recommendation system using composition."""

from typing import List
from menu import Menu
from meal_items import AbstractMealItem


class Recommendations:
    """Meal recommendation system."""

    def __init__(self, menu: Menu):
        self._menu = menu
        self._history = []

    def add_to_history(self, meal_id: str) -> None:
        """Track a meal selection."""
        self._history.append(meal_id)

    def get_history(self) -> List[str]:
        """Get meal history."""
        return list(self._history)

    def recommend_by_value(self, top_k: int = 3) -> List[AbstractMealItem]:
        """Recommend meals by value score."""
        meals = self._menu.get_all_meals()
        scored = [(m.calculate_value_score(), m) for m in meals]
        scored.sort(reverse=True)
        return [meal for _, meal in scored[:top_k]]

    def recommend_by_diet(self, diet: str, top_k: int = 3) -> List[AbstractMealItem]:
        """Recommend meals by diet type."""
        filtered = self._menu.filter_by_diet(diet)
        scored = [(m.calculate_value_score(), m) for m in filtered]
        scored.sort(reverse=True)
        return [meal for _, meal in scored[:top_k]]